package com.landgo.userservice.health;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Deep health endpoint for user-service.
 *
 * <p>Exposed at {@code /health-check} rather than through Spring Actuator,
 * and this is the important part of the design:
 *
 * <p>/health-check is not polled by a load balancer (IaC shows these polled paths: /, /actuator/health, /health), so a failing probe cannot cause the platform to restart healthy instances
 *
 * <p>If these probes contributed to {@code /actuator/health}, a brief outage
 * in any one dependency would mark every task unhealthy, the platform would
 * drain and restart them all, and a dependency hiccup would escalate into a
 * self-inflicted outage. Keeping the two endpoints separate is what prevents
 * that.
 *
 * <p>Generated by repo-orchestrator from discovered capabilities.
 */
@RestController
@RequestMapping("/health-check")
public class HealthCheckController {

    private static final Logger log = LoggerFactory.getLogger(HealthCheckController.class);

    private final List<DeepHealthProbe> probes;

    public HealthCheckController(List<DeepHealthProbe> probes) {
        this.probes = probes;
    }

    @GetMapping
    public ResponseEntity<Map<String, Object>> check() {
        Map<String, Object> results = new LinkedHashMap<>();
        boolean anyDown = false;

        for (DeepHealthProbe probe : probes) {
            ProbeResult result;
            try {
                result = probe.check();
            } catch (Exception e) {
                // A probe that throws is a broken probe, not necessarily a
                // broken dependency -- but it still cannot be reported as UP.
                log.warn("Probe {} threw", probe.name(), e);
                result = ProbeResult.down(probe.name(), 0L, e.toString(), null);
            }
            anyDown |= result.isDown();

            Map<String, Object> body = new LinkedHashMap<>();
            body.put("status", result.getStatus());
            body.put("latencyMs", result.getLatencyMs());
            body.putAll(result.getDetails());
            results.put(result.getName(), body);
        }

        Map<String, Object> response = new LinkedHashMap<>();
        response.put("service", "user-service");
        response.put("status", anyDown ? "DOWN" : "UP");
        response.put("checkedAt", Instant.now().toString());
        response.put("probes", results);

        return ResponseEntity.status(anyDown ? 503 : 200).body(response);
    }
}
